In [1]:
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

print(tf.__version__)


1.15.4


In [2]:
datasetfilename = 'saseendataset.npz'

with np.load(datasetfilename, allow_pickle=True) as data:
    dataImages = data['images']
    dataLabel = data['labels']
    dataLabelNames = data['labelnames']
    
print(dataImages.shape)
print(dataLabel.shape)
print(dataLabelNames.shape)

(24,)
(24,)
(24,)


In [3]:
dataImages.dtype, dataLabel.dtype, dataLabelNames.dtype

(dtype('O'), dtype('int32'), dtype('<U10'))

In [4]:
print(dataLabel)
print(dataLabelNames)

[5 0 1 2 3 4 6 7 8 0 1 3 4 6 7 5 0 1 2 3 4 6 7 8]
['JC' 'afiq' 'azureen' 'gavin' 'goke' 'inamul' 'mahmuda' 'numan'
 'saseendran' 'afiq' 'azureen' 'goke' 'inamul' 'mahmuda' 'numan' 'JC'
 'afiq' 'azureen' 'gavin' 'goke' 'inamul' 'mahmuda' 'numan' 'saseendran']


In [5]:
classNames = sorted(np.unique(dataLabelNames))
print(classNames)

['JC', 'afiq', 'azureen', 'gavin', 'goke', 'inamul', 'mahmuda', 'numan', 'saseendran']


In [7]:
import cv2 as cv

N = len(dataImages)
shape = (N, 200,200,3)

y = np.empty(shape, dtype='uint8')

for i in range(N):
    y[i] = cv.resize(dataImages[i], [200,200], interpolation=cv.INTER_NEAREST)
    
dataImages.dtype, y.dtype, y.shape

dataImages = y

SystemError: new style getargs format but argument is not a tuple

In [8]:
# Split the data to train and test
trainImages, testImages, trainLabels, testLabels = train_test_split(dataImages, dataLabel, test_size=0.3, random_state=42)

print(dataImages.shape)
print(dataLabel)

print(trainImages.shape)
print(testImages.shape)
print(testLabels)

(24,)
[5 0 1 2 3 4 6 7 8 0 1 3 4 6 7 5 0 1 2 3 4 6 7 8]
(16,)
(8,)
[8 0 5 2 3 0 6 0]


In [ ]:
# classNames = sorted(np.unique(dataLabelNames))
# dataLabel[0]

In [ ]:
# plt.figure()

# i = 0
# plt.imshow(trainImages[i])
# plt.title(f'{trainLabels[i]}')
# # plt.xlabel(classNames[dataLabel[i]])
# plt.show()

In [9]:
import numpy as np

print(trainImages[0].shape)
print(trainImages[1].shape)

(126, 164, 3)
(112, 155, 3)


In [10]:
for i in range(len(trainImages)):
    trainImages[i] = cv.resize(trainImages[i], [200,200], interpolation=cv.INTER_NEAREST)


SystemError: new style getargs format but argument is not a tuple

In [11]:
inputShape = trainImages[0].shape
outputShape = len(classNames)

inputShape, outputShape

((126, 164, 3), 9)

In [12]:
trainImages = trainImages / 255
testImages = testImages / 255

In [13]:
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=inputShape),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(outputShape)
])

model.summary()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 61992)             0         
_________________________________________________________________
dense (Dense)                (None, 128)               7935104   
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_2 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_3 (Dense)              (None, 9)                 1161      
Total params: 7,969,289
Trainable params: 7,969,289
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile(optimizer='adam', loss= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

In [16]:
model.fit(trainImages, trainLabels, epochs=12)

ValueError: Error when checking input: expected flatten_input to have 4 dimensions, but got array with shape (16, 1)

In [17]:
testLoss, testAcc = model.evaluate(testImages, testLabels, verbose=2)

print('\nTest accuracy:', testAcc)

ValueError: Error when checking input: expected flatten_input to have 4 dimensions, but got array with shape (8, 1)

In [18]:
predictions = model.predict(testImages)
predictions[0]

ValueError: Error when checking input: expected flatten_input to have 4 dimensions, but got array with shape (8, 1)

In [19]:
i = 1
predictedLabel = np.argmax(predictions[i])
predictedLabel, testLabels[i], predictedLabel == testLabels[i]


NameError: name 'predictions' is not defined