In [ ]:
#1. Create an array of shape(10,10) with uint8 random values
#2. print the shape, size and dimension
#3. compute the sum of third row to the last row
#4. compute the average of the columns                 

In [1]:
def array_properties(a):
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("size = ", a.size)
    print()

In [33]:
import numpy as np

r2 = np.random.randint(0,256,(10,10),dtype=np.uint8)

#print(r2)
array_properties(r2)

dim =  2
shape =  (10, 10)
size =  100



In [40]:
print('Rows from third to last :\n ',r2[2:])
print('\nSum of third row to the last row: ',np.sum(r2[2:]))

Rows from third to last :
  [[  0  65 171  90  48  85 191   6 169 181]
 [195  84 237   1 191 189 190 215 155  42]
 [172  44 236 195   8 205 182  85 197 118]
 [227 157 164 136   4  52 134 176 160 181]
 [ 82 208 136 140 237 139 211 153  19  88]
 [131 221 162 223 241 105 163 210  22  19]
 [252  21   1  93 232 147 231 216  42  54]
 [ 48 244 194 211 247 129  88 101 129 241]]

Sum of third row to the last row:  11169


In [47]:
print('\nSum of third row to the last row: ',np.mean(r2[0:]))


Sum of third row to the last row:  138.76
