In [1]:
#1. Create an array of shape (100,100,3) of unsigned integer of 8 bits (uint8) filled with random values between 0 to 256.
#2. Find the values that are less than 30, 50, 100, 250.
#3. Copy and change the value that are less than 110 to 0 and others to 255.
#4. Split the array into 4 parts vertivally and horizontally
#5. Hint use random seed of 12345

In [2]:
def array_properties(a):
    print("a = \n", a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

In [3]:
import numpy as np
np.random.seed(12345)
arr = np.random.randint(0,256,(100,100,3),dtype=np.uint8)
array_properties(arr)

a = 
 [[[226  81 251]
  [237 229  45]
  [225 227  29]
  ...
  [152 224 239]
  [147 249 235]
  [ 22  77  13]]

 [[  5 116 247]
  [167  74 150]
  [ 36 229  76]
  ...
  [ 85 171 127]
  [  1 129 245]
  [243  42  21]]

 [[192  98 195]
  [ 57  77 233]
  [  7 230   8]
  ...
  [ 64 151 156]
  [202  15 104]
  [221 112 230]]

 ...

 [[ 61 149 122]
  [ 60 176 204]
  [102  45  44]
  ...
  [136 101 177]
  [ 42 177 221]
  [138 102  84]]

 [[120  73 190]
  [175  32  56]
  [211 192 194]
  ...
  [239 223  11]
  [ 46   7 253]
  [ 35 125 235]]

 [[212 239  76]
  [ 92 178 105]
  [ 90 242 147]
  ...
  [213 192  46]
  [198 244 112]
  [156 214 199]]]
dim =  3
shape =  (100, 100, 3)
datatype =  uint8
size =  30000



In [4]:
bool30 = arr <30
array_properties(bool30)

a = 
 [[[False False False]
  [False False False]
  [False False  True]
  ...
  [False False False]
  [False False False]
  [ True False  True]]

 [[ True False False]
  [False False False]
  [False False False]
  ...
  [False False False]
  [ True False False]
  [False False  True]]

 [[False False False]
  [False False False]
  [ True False  True]
  ...
  [False False False]
  [False  True False]
  [False False False]]

 ...

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False  True]
  [False  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False False]
  [False False False]
  [False False False]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000



In [5]:
bool30 = bool30 == True
array_properties(bool30)

result_30 = arr[bool30]
print("Values less than 30 are :")
array_properties(result_30)


a = 
 [[[False False False]
  [False False False]
  [False False  True]
  ...
  [False False False]
  [False False False]
  [ True False  True]]

 [[ True False False]
  [False False False]
  [False False False]
  ...
  [False False False]
  [ True False False]
  [False False  True]]

 [[False False False]
  [False False False]
  [ True False  True]
  ...
  [False False False]
  [False  True False]
  [False False False]]

 ...

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False  True]
  [False  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False False]
  [False False False]
  [False False False]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000

Values less than 30 are :
a = 
 [29  8 21 ...  5 28 24]
dim =  1
shape =  (3516,)
da

In [6]:
bool50 = arr <50
array_properties(bool50)


a = 
 [[[False False False]
  [False False  True]
  [False False  True]
  ...
  [False False False]
  [False False False]
  [ True False  True]]

 [[ True False False]
  [False False False]
  [ True False False]
  ...
  [False False False]
  [ True False False]
  [False  True  True]]

 [[False False False]
  [False False False]
  [ True False  True]
  ...
  [False False False]
  [False  True False]
  [False False False]]

 ...

 [[False False False]
  [False False False]
  [False  True  True]
  ...
  [False False False]
  [ True False False]
  [False False False]]

 [[False False False]
  [False  True False]
  [False False False]
  ...
  [False False  True]
  [ True  True False]
  [ True False False]]

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False  True]
  [False False False]
  [False False False]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000



In [7]:
bool50 = bool50 == True
array_properties(bool50)

result_50 = arr[bool50]
print("Values that are less than 50 are :")
array_properties(result_50)

a = 
 [[[False False False]
  [False False  True]
  [False False  True]
  ...
  [False False False]
  [False False False]
  [ True False  True]]

 [[ True False False]
  [False False False]
  [ True False False]
  ...
  [False False False]
  [ True False False]
  [False  True  True]]

 [[False False False]
  [False False False]
  [ True False  True]
  ...
  [False False False]
  [False  True False]
  [False False False]]

 ...

 [[False False False]
  [False False False]
  [False  True  True]
  ...
  [False False False]
  [ True False False]
  [False False False]]

 [[False False False]
  [False  True False]
  [False False False]
  ...
  [False False  True]
  [ True  True False]
  [ True False False]]

 [[False False False]
  [False False False]
  [False False False]
  ...
  [False False  True]
  [False False False]
  [False False False]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000

Values that are less than 50 are :
a = 
 [45 29  8 ... 35 24 46]
dim =  1
shape =  (

In [8]:
bool100 = arr <100
array_properties(bool100)

a = 
 [[[False  True False]
  [False False  True]
  [False False  True]
  ...
  [False False False]
  [False False False]
  [ True  True  True]]

 [[ True False False]
  [False  True False]
  [ True False  True]
  ...
  [ True False False]
  [ True False False]
  [False  True  True]]

 [[False  True False]
  [ True  True False]
  [ True False  True]
  ...
  [ True False False]
  [False  True False]
  [False False False]]

 ...

 [[ True False False]
  [ True False False]
  [False  True  True]
  ...
  [False False False]
  [ True False False]
  [False False  True]]

 [[False  True False]
  [False  True  True]
  [False False False]
  ...
  [False False  True]
  [ True  True False]
  [ True False False]]

 [[False False  True]
  [ True False False]
  [ True False False]
  ...
  [False False  True]
  [False False False]
  [False False False]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000



In [9]:
bool100 = bool100 == True
array_properties(bool100)

result_100 = arr[bool100]
print("Values that are less than 100 are :")
array_properties(result_100)

a = 
 [[[False  True False]
  [False False  True]
  [False False  True]
  ...
  [False False False]
  [False False False]
  [ True  True  True]]

 [[ True False False]
  [False  True False]
  [ True False  True]
  ...
  [ True False False]
  [ True False False]
  [False  True  True]]

 [[False  True False]
  [ True  True False]
  [ True False  True]
  ...
  [ True False False]
  [False  True False]
  [False False False]]

 ...

 [[ True False False]
  [ True False False]
  [False  True  True]
  ...
  [False False False]
  [ True False False]
  [False False  True]]

 [[False  True False]
  [False  True  True]
  [False False False]
  ...
  [False False  True]
  [ True  True False]
  [ True False False]]

 [[False False  True]
  [ True False False]
  [ True False False]
  ...
  [False False  True]
  [False False False]
  [False False False]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000

Values that are less than 100 are :
a = 
 [81 45 29 ... 75 24 46]
dim =  1
shape =  

In [10]:
bool250 = arr <250
array_properties(bool250)

a = 
 [[[ True  True False]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 ...

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True False]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000



In [11]:
bool250 = bool250 == True
array_properties(bool250)

result_250 = arr[bool250]
print("Values that are less than 250 are :")
array_properties(result_250)

a = 
 [[[ True  True False]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 ...

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True False]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000

Values that are less than 250 are :
a = 
 [226  81 237 ... 156 214 199]
dim =  1
sha

In [12]:
arr_c = np.copy(arr)

In [13]:
bool110 = arr_c <110
array_properties(bool110)


a = 
 [[[False  True False]
  [False False  True]
  [False False  True]
  ...
  [False False False]
  [False False False]
  [ True  True  True]]

 [[ True False False]
  [False  True False]
  [ True False  True]
  ...
  [ True False False]
  [ True False False]
  [False  True  True]]

 [[False  True False]
  [ True  True False]
  [ True False  True]
  ...
  [ True False False]
  [False  True  True]
  [False False False]]

 ...

 [[ True False False]
  [ True False False]
  [ True  True  True]
  ...
  [False  True False]
  [ True False False]
  [False  True  True]]

 [[False  True False]
  [False  True  True]
  [False False False]
  ...
  [False False  True]
  [ True  True False]
  [ True False False]]

 [[False False  True]
  [ True False  True]
  [ True False False]
  ...
  [False False  True]
  [False False False]
  [False False False]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000



In [14]:
bool0 = bool110 == True
bool255 = bool110 == False
array_properties(bool110)


arr_c[bool0] = 0
arr_c[bool255] = 255

array_properties(arr_c)


a = 
 [[[False  True False]
  [False False  True]
  [False False  True]
  ...
  [False False False]
  [False False False]
  [ True  True  True]]

 [[ True False False]
  [False  True False]
  [ True False  True]
  ...
  [ True False False]
  [ True False False]
  [False  True  True]]

 [[False  True False]
  [ True  True False]
  [ True False  True]
  ...
  [ True False False]
  [False  True  True]
  [False False False]]

 ...

 [[ True False False]
  [ True False False]
  [ True  True  True]
  ...
  [False  True False]
  [ True False False]
  [False  True  True]]

 [[False  True False]
  [False  True  True]
  [False False False]
  ...
  [False False  True]
  [ True  True False]
  [ True False False]]

 [[False False  True]
  [ True False  True]
  [ True False False]
  ...
  [False False  True]
  [False False False]
  [False False False]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000

a = 
 [[[255   0 255]
  [255 255   0]
  [255 255   0]
  ...
  [255 255 255]
  [255 2

In [15]:
h4 = np.hsplit(arr_c,4)
print(h4)

[array([[[255,   0, 255],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [255, 255,   0],
        [  0, 255,   0],
        [255,   0,   0]],

       [[  0, 255, 255],
        [255,   0, 255],
        [  0, 255,   0],
        ...,
        [255, 255,   0],
        [255, 255, 255],
        [  0, 255,   0]],

       [[255,   0, 255],
        [  0,   0, 255],
        [  0, 255,   0],
        ...,
        [255, 255,   0],
        [  0,   0, 255],
        [255, 255,   0]],

       ...,

       [[  0, 255, 255],
        [  0, 255, 255],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [  0, 255,   0],
        [255, 255,   0]],

       [[255,   0, 255],
        [255,   0,   0],
        [255, 255, 255],
        ...,
        [  0, 255,   0],
        [  0,   0,   0],
        [  0, 255, 255]],

       [[255, 255,   0],
        [  0, 255,   0],
        [  0, 255, 255],
        ...,
        [  0,   0,   0],
        [255, 255,   0],
        [  0,   0,   0]

In [16]:
v4 = np.vsplit(arr_c,5)
print(v4)

[array([[[255,   0, 255],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0,   0]],

       [[  0, 255, 255],
        [255,   0, 255],
        [  0, 255,   0],
        ...,
        [  0, 255, 255],
        [  0, 255, 255],
        [255,   0,   0]],

       [[255,   0, 255],
        [  0,   0, 255],
        [  0, 255,   0],
        ...,
        [  0, 255, 255],
        [255,   0,   0],
        [255, 255, 255]],

       ...,

       [[  0,   0, 255],
        [255,   0, 255],
        [  0, 255,   0],
        ...,
        [255, 255,   0],
        [255, 255, 255],
        [255, 255,   0]],

       [[255,   0, 255],
        [255, 255,   0],
        [255, 255, 255],
        ...,
        [255, 255,   0],
        [255,   0,   0],
        [255, 255, 255]],

       [[  0, 255, 255],
        [255, 255, 255],
        [255, 255,   0],
        ...,
        [255, 255, 255],
        [255,   0,   0],
        [255, 255, 255]