In [1]:
#1. Create a random array A, of shape (6,6) using randint and seed.
#2. Convert the array A, to an identity matrix I.



I = 

\begin{matrix}
    1 & 0 & 0 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 & 0 & 0 \\
    0 & 0 & 1 & 0 & 0 & 0 \\
    0 & 0 & 0 & 1 & 0 & 0 \\
    0 & 0 & 0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 0 & 0 & 1 \\
\end{matrix}



In [2]:
def array_properties(a, label='a'):
    print(label, '= ')
    print(a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

In [3]:

from numpy import linalg as lg
import numpy as np
np.random.seed(2)
a = np.random.randint(0,10,(6,6))
array_properties(a , 'A')



A = 
[[8 8 6 2 8 7]
 [2 1 5 4 4 5]
 [7 3 6 4 3 7]
 [6 1 3 5 8 4]
 [6 3 9 2 0 4]
 [2 4 1 7 8 2]]
dim =  2
shape =  (6, 6)
datatype =  int32
size =  36



In [4]:
a_inv = lg.inv(a)

id_1 = a @ a_inv
id_1 = np.rint(id_1).astype(int)
array_properties(id_1 , 'Identity Matrix 1')

Identity Matrix 1 = 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
dim =  2
shape =  (6, 6)
datatype =  int32
size =  36



In [5]:
id_2 =  a_inv @ a
id_2 = np.rint(id_2).astype(int)
array_properties(id_2 , 'Identity Matrix 2')

Identity Matrix 2 = 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
dim =  2
shape =  (6, 6)
datatype =  int32
size =  36



In [6]:

id_3 = np.copy(a)
m,n = id_3.shape

np.fill_diagonal(id_3,1)
for i in range(n):
    #I[i,i] = np.array([1])
    id_3[i,i+1:] = np.array([0])
    id_3[i+1:,i] = np.array([0])
    
array_properties(id_3,'Identity Matrix 3')



Identity Matrix 3 = 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
dim =  2
shape =  (6, 6)
datatype =  int32
size =  36



In [7]:
m,n = a.shape

# create identity matrix of 
id_4 = np.eye(n).astype(int)

array_properties(id_4,'Identity Matrix 4')



Identity Matrix 4 = 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
dim =  2
shape =  (6, 6)
datatype =  int32
size =  36



In [8]:

c1 = id_4 == id_1
c2 = id_4 == id_2
c3 = id_1 == id_2


print("For ID 1 and ID 4  : ")
array_properties(c1,'I')
print()
print("For ID 2 and ID 4 : ")
array_properties(c2,'I')
print()
print("For ID 1 and ID 2 : ")
array_properties(c3,'I')

For ID 1 and ID 4  : 
I = 
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
dim =  2
shape =  (6, 6)
datatype =  bool
size =  36


For ID 2 and ID 4 : 
I = 
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
dim =  2
shape =  (6, 6)
datatype =  bool
size =  36


For ID 1 and ID 2 : 
I = 
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
dim =  2
shape =  (6, 6)
datatype =  bool
size =  36

