In [1]:
#1. Create an array of shape (100,100,3) of unsigned integer of 8 bits (uint8) filled with random values between 0 to 256.
#2. Find the values that are less than 30, 50, 100, 250.
#3. Copy and change the value that are less than 110 to 0 and others to 255.
#4. Split the array into 4 parts vertivally and horizontally
#5. Hint use random seed of 12345

In [2]:
def array_properties(a):
    print("a = \n", a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

In [3]:
import numpy as np
np.random.seed(12345)
arr = np.random.randint(0,256,(10,10,3),dtype=np.uint8)
array_properties(arr)

a = 
 [[[226  81 251]
  [237 229  45]
  [225 227  29]
  [253 253  80]
  [129   8 118]
  [ 33 164  77]
  [ 21  47 169]
  [173  45  10]
  [254  15  94]
  [ 52 126  81]]

 [[145 211 101]
  [109  86 145]
  [ 34  66  54]
  [136  29 158]
  [117 152   1]
  [187 208 244]
  [118 108 234]
  [246 113 205]
  [ 64 118  59]
  [157  54 167]]

 [[142  26 122]
  [236 105  88]
  [184 191  91]
  [ 76 185  95]
  [247  90  80]
  [167 118  85]
  [172  39 208]
  [ 60 106 191]
  [114 163 112]
  [228 201  50]]

 [[ 24 246  11]
  [177 219   6]
  [ 77 188  37]
  [  2 138 230]
  [159  74  81]
  [240  63  27]
  [210  22  20]
  [102 166 216]
  [119  76   7]
  [121 170 206]]

 [[ 43 144  10]
  [168 231  64]
  [137 160  23]
  [224  79 207]
  [ 29 196 109]
  [232 184 235]
  [ 70 223 183]
  [ 13 112 142]
  [ 31  37 243]
  [246 189 242]]

 [[  4 215  97]
  [113  67 185]
  [ 91 199 236]
  [ 12  87  67]
  [121 164  36]
  [104 101 206]
  [ 64  10 171]
  [183 239 239]
  [ 73 238 131]
  [145 180 119]]

 [[252  10  49]
  [ 93

In [4]:
bool30 = arr <30
array_properties(bool30)

a = 
 [[[False False False]
  [False False False]
  [False False  True]
  [False False False]
  [False  True False]
  [False False False]
  [ True False False]
  [False False  True]
  [False  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False  True False]
  [False False  True]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False  True False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[ True False  True]
  [False False  True]
  [False False False]
  [ True False False]
  [False False False]
  [False False  True]
  [False  True  True]
  [False False False]
  [False False  True]
  [False False False]]

 [[False False  True]
  [False False False]
  [False False  True]
  [False False False]
  [ True False Fal

In [5]:
bool30 = bool30 == True
array_properties(bool30)

result_30 = arr[bool30]
print("Values less than 30 are :")
array_properties(result_30)


a = 
 [[[False False False]
  [False False False]
  [False False  True]
  [False False False]
  [False  True False]
  [False False False]
  [ True False False]
  [False False  True]
  [False  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False  True False]
  [False False  True]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False  True False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[ True False  True]
  [False False  True]
  [False False False]
  [ True False False]
  [False False False]
  [False False  True]
  [False  True  True]
  [False False False]
  [False False  True]
  [False False False]]

 [[False False  True]
  [False False False]
  [False False  True]
  [False False False]
  [ True False Fal

In [6]:
bool50 = arr <50
array_properties(bool50)


a = 
 [[[False False False]
  [False False  True]
  [False False  True]
  [False False False]
  [False  True False]
  [ True False False]
  [ True  True False]
  [False  True  True]
  [False  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [ True False False]
  [False  True False]
  [False False  True]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False  True False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False  True False]
  [False False False]
  [False False False]
  [False False False]]

 [[ True False  True]
  [False False  True]
  [False False  True]
  [ True False False]
  [False False False]
  [False False  True]
  [False  True  True]
  [False False False]
  [False False  True]
  [False False False]]

 [[ True False  True]
  [False False False]
  [False False  True]
  [False False False]
  [ True False Fal

In [7]:
bool50 = bool50 == True
array_properties(bool50)

result_50 = arr[bool50]
print("Values that are less than 50 are :")
array_properties(result_50)

a = 
 [[[False False False]
  [False False  True]
  [False False  True]
  [False False False]
  [False  True False]
  [ True False False]
  [ True  True False]
  [False  True  True]
  [False  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [ True False False]
  [False  True False]
  [False False  True]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False  True False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False False False]
  [False  True False]
  [False False False]
  [False False False]
  [False False False]]

 [[ True False  True]
  [False False  True]
  [False False  True]
  [ True False False]
  [False False False]
  [False False  True]
  [False  True  True]
  [False False False]
  [False False  True]
  [False False False]]

 [[ True False  True]
  [False False False]
  [False False  True]
  [False False False]
  [ True False Fal

In [8]:
bool100 = arr <100
array_properties(bool100)

a = 
 [[[False  True False]
  [False False  True]
  [False False  True]
  [False False  True]
  [False  True False]
  [ True False  True]
  [ True  True False]
  [False  True  True]
  [False  True  True]
  [ True False  True]]

 [[False False False]
  [False  True False]
  [ True  True  True]
  [False  True False]
  [False False  True]
  [False False False]
  [False False False]
  [False False False]
  [ True False  True]
  [False  True False]]

 [[False  True False]
  [False False  True]
  [False False  True]
  [ True False  True]
  [False  True  True]
  [False False  True]
  [False  True False]
  [ True False False]
  [False False False]
  [False False  True]]

 [[ True False  True]
  [False False  True]
  [ True False  True]
  [ True False False]
  [False  True  True]
  [False  True  True]
  [False  True  True]
  [False False False]
  [False  True  True]
  [False False False]]

 [[ True False  True]
  [False False  True]
  [False False  True]
  [False  True False]
  [ True False Fal

In [9]:
bool100 = bool100 == True
array_properties(bool100)

result_100 = arr[bool100]
print("Values that are less than 100 are :")
array_properties(result_100)

a = 
 [[[False  True False]
  [False False  True]
  [False False  True]
  [False False  True]
  [False  True False]
  [ True False  True]
  [ True  True False]
  [False  True  True]
  [False  True  True]
  [ True False  True]]

 [[False False False]
  [False  True False]
  [ True  True  True]
  [False  True False]
  [False False  True]
  [False False False]
  [False False False]
  [False False False]
  [ True False  True]
  [False  True False]]

 [[False  True False]
  [False False  True]
  [False False  True]
  [ True False  True]
  [False  True  True]
  [False False  True]
  [False  True False]
  [ True False False]
  [False False False]
  [False False  True]]

 [[ True False  True]
  [False False  True]
  [ True False  True]
  [ True False False]
  [False  True  True]
  [False  True  True]
  [False  True  True]
  [False False False]
  [False  True  True]
  [False False False]]

 [[ True False  True]
  [False False  True]
  [False False  True]
  [False  True False]
  [ True False Fal

In [10]:
bool250 = arr <250
array_properties(bool250)

a = 
 [[[ True  True False]
  [ True  True  True]
  [ True  True  True]
  [False False  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [False  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  Tr

In [11]:
bool250 = bool250 == True
array_properties(bool250)

result_250 = arr[bool250]
print("Values that are less than 250 are :")
array_properties(result_250)

a = 
 [[[ True  True False]
  [ True  True  True]
  [ True  True  True]
  [False False  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [False  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  Tr

In [12]:
arr_c = np.copy(arr)

In [13]:
bool110 = arr_c <110
array_properties(bool110)


a = 
 [[[False  True False]
  [False False  True]
  [False False  True]
  [False False  True]
  [False  True False]
  [ True False  True]
  [ True  True False]
  [False  True  True]
  [False  True  True]
  [ True False  True]]

 [[False False  True]
  [ True  True False]
  [ True  True  True]
  [False  True False]
  [False False  True]
  [False False False]
  [False  True False]
  [False False False]
  [ True False  True]
  [False  True False]]

 [[False  True False]
  [False  True  True]
  [False False  True]
  [ True False  True]
  [False  True  True]
  [False False  True]
  [False  True False]
  [ True  True False]
  [False False False]
  [False False  True]]

 [[ True False  True]
  [False False  True]
  [ True False  True]
  [ True False False]
  [False  True  True]
  [False  True  True]
  [False  True  True]
  [ True False False]
  [False  True  True]
  [False False False]]

 [[ True False  True]
  [False False  True]
  [False False  True]
  [False  True False]
  [ True False  Tr

In [14]:
bool0 = bool110 == True
bool255 = bool110 == False
array_properties(bool110)


arr_c[bool0] = 0
arr_c[bool255] = 255

array_properties(arr_c)


a = 
 [[[False  True False]
  [False False  True]
  [False False  True]
  [False False  True]
  [False  True False]
  [ True False  True]
  [ True  True False]
  [False  True  True]
  [False  True  True]
  [ True False  True]]

 [[False False  True]
  [ True  True False]
  [ True  True  True]
  [False  True False]
  [False False  True]
  [False False False]
  [False  True False]
  [False False False]
  [ True False  True]
  [False  True False]]

 [[False  True False]
  [False  True  True]
  [False False  True]
  [ True False  True]
  [False  True  True]
  [False False  True]
  [False  True False]
  [ True  True False]
  [False False False]
  [False False  True]]

 [[ True False  True]
  [False False  True]
  [ True False  True]
  [ True False False]
  [False  True  True]
  [False  True  True]
  [False  True  True]
  [ True False False]
  [False  True  True]
  [False False False]]

 [[ True False  True]
  [False False  True]
  [False False  True]
  [False  True False]
  [ True False  Tr

In [18]:
h4 = np.hsplit(arr_c,5)
print(h4)

[array([[[255,   0, 255],
        [255, 255,   0]],

       [[255, 255,   0],
        [  0,   0, 255]],

       [[255,   0, 255],
        [255,   0,   0]],

       [[  0, 255,   0],
        [255, 255,   0]],

       [[  0, 255,   0],
        [255, 255,   0]],

       [[  0, 255,   0],
        [255,   0, 255]],

       [[255,   0,   0],
        [  0, 255, 255]],

       [[255, 255,   0],
        [255, 255,   0]],

       [[  0, 255, 255],
        [  0, 255,   0]],

       [[  0, 255, 255],
        [  0, 255, 255]]], dtype=uint8), array([[[255, 255,   0],
        [255, 255,   0]],

       [[  0,   0,   0],
        [255,   0, 255]],

       [[255, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255, 255]],

       [[255, 255,   0],
        [255,   0, 255]],

       [[  0, 255, 255],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [255, 255, 255]],

       [[  0, 255,   0],
        [255, 255,   0]],

       [[255, 255,   0],
        [  0, 255, 255]]

In [17]:
v4 = np.vsplit(arr_c,5)
print(v4)

ValueError: array split does not result in an equal division